### ISSUE TITLE
Can not use keras_to_tensorflow.py

### ISSUE THREAD

**Issue by yezilove** [amir-abdi/keras_to_tensorflow#14]
when i use the command:

python3 keras_to_tensorflow.py -input_model_file my_model.h5 -output_model_file model.pb

it return an error, error message as follows:

Traceback (most recent call last):
  File "keras_to_tensorflow.py", line 95, in <module>
  net_model = load_model(weight_file_path)
  File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 239, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/generic_utils.py", line 139, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 2490, in from_config
    process_layer(layer_data)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 2476, in process_layer
    custom_objects=custom_objects)
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/generic_utils.py", line 133, in deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown layer: BatchNorm

what  shall i do? thank you !

**Comment by amir-abdi** [comment]
The error is raised when you were trying to load the model. The error is regarding the `BatchNorm` layer. It basically means that either the keras version used to create the model, does not match the keras version you are using to convert the model.

**Comment by amir-abdi** [comment]
@yezilove 
I assume the problem is resolved by updating your libraries; so, I close the issue.
Reopen it otherwise.

**Comment by rnmehta726** [comment]
Hello! Even if I change the Keras version to the one used when the model was trained, I still get the same error. Are there any other solutions?
